title: Ben Lewis (@bupedev)
author: Ben Lewis
email: ben@bupe.dev
phone: (+61) 439 833 763
location: Brisbane, Australia

description: >-
  Software engineer from Brisbane, Australia, currently building strategic 
  mine planning software for Deswik. When I am not spending time with my wife
  and my daughter, I enjoy creative coding and making generative art. 

domain: bupe.dev
baseurl: /bupedev.github.io
url: http://bupedev.github.io

socials:
  - 
      name: LinkedIn
      id: lewisbj
      url: linkedin.com/in/
      icon: fa-brands fa-linkedin
  - 
      name: Twitter
      id: bupedev
      url: twitter.com/
      icon: fa-brands fa-square-twitter
  - 
      name: Instagram
      id: bupedev
      url: instagram.com/
      icon: fa-brands fa-square-instagram
  - 
      name: Github
      id: bupedev
      url: github.com/
      icon: fa-brands fa-square-github
  -
      name: E-Mail
      id: "ben@bupe.dev"
      url: "mailto:"
      icon: fa-solid fa-square-envelope

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
- cv

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
