title: Ben Lewis (@bupedev)
author: Ben Lewis
email: ben@bupe.dev
phone: (+61) 439 833 763
location: Brisbane, Australia

description: >-
  Software engineer from Brisbane, Australia, currently building strategic 
  mine planning software for Deswik. When I am not spending time with my wife
  and my daughter, I enjoy creative coding and making generative art. 

domain: bupe.dev
baseurl: ""
url: https://bupe.dev

linkedin_username: lewisbj
instagram_username: bupedev
twitter_username: bupedev
github_username:  bupedev

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
- cv

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
